name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.6, 3.7]
        openeye: ["true", "false"]
    env:
      PYVER: ${{ matrix.python-version }}
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      COV: --cov=openff/cli --cov-report=xml --cov-config=setup.cfg --cov-append

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      name: Install both RDKit and OpenEye toolkits
      if: ${{ matrix.openeye == 'TRUE' }}
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        channel-priority: true
        environment-file: devtools/conda-envs/test_env.yaml
        auto-activate-base: false

    - uses: conda-incubator/setup-miniconda@v2
      name: Install only RDKit
      if: ${{ matrix.openeye == 'FALSE' }}
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: test
        channel-priority: true
        environment-file: devtools/conda-envs/rdkit_env.yaml
        auto-activate-base: false

    - name: Check installed toolkits
      shell: bash -l {0}
      run: |
        if [[ "$OPENEYE" == true ]]; then
          python -c "from openforcefield.utils.toolkits import OPENEYE_AVAILABLE; assert OPENEYE_AVAILABLE, 'OpenEye unavailable'"
        fi
        if [[ "$OPENEYE" == false ]]; then
          if [[ $(conda list | grep openeye-toolkits) ]]; then
            conda remove --force openeye-toolkits --yes
          fi
          python -c "from openforcefield.utils.toolkits import OPENEYE_AVAILABLE; assert not OPENEYE_AVAILABLE, 'OpenEye unexpectedly found'"
        fi

    - name: Make oe_license.txt file from GH org secret "OE_LICENSE"
      if: ${{ matrix.openeye == 'TRUE' }}
      shell: bash
      env:
        OE_LICENSE_TEXT: ${{ secrets.OE_LICENSE }}
      run: |
        echo "${OE_LICENSE_TEXT}" > ${OE_LICENSE}

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info --all
        conda list

    - name: Install package
      shell: bash -l {0}
      run: |
        python setup.py develop --no-deps

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v $COV openff/cli/tests

    - name: Codecov
      uses: codecov/codecov-action@v1.5.0
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
